// import { Open_Sans } from 'next/font/google'
import localFont from 'next/font/local'
import Header from '@/components/Header'
import { theme } from './theme/theme'
import { ThemeProvider } from "@mui/material/styles";
import '../styles/Global.scss'
// this ensures that the icon CSS is loaded immediately before attempting to render icons
import '@fortawesome/fontawesome-svg-core/styles.css';
import { Box, Container } from '@mui/material';

// const open_sans = Open_Sans({ 
//   weight: ['300', '400', '700', '800'],
//   subsets: ['latin'],
//   variable: '--font-open_sans',
// })

const Gilroy = localFont({
  src: [
    {
      path: '../fonts/Gilroy-ExtraBold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../fonts/Gilroy-Light.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-gilroy',
})

export const metadata = {
  title: 'Next JS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body className={Gilroy.className}>
          <Header />
          <Box component="div" className='mainContent'>
            {children}
          </Box>
        </body>
      </ThemeProvider>
    </html>
  )
}
